package com.thenextlvl.foliagui.internal.export;

import com.thenextlvl.foliagui.api.GUI;
import com.thenextlvl.foliagui.api.export.GUIExporter;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.io.StringWriter;
import java.io.Writer;

/**
 * Java Builder 代码导出器
 * 生成可直接使用的 Java 代码
 *
 * @author TheNextLvl
 */
public class JavaBuilderExporter implements GUIExporter {

    @Override
    public @NotNull String getFormat() {
        return "Java Builder";
    }

    @Override
    public @NotNull String getFileExtension() {
        return "java";
    }

    @Override
    public @NotNull String getContentType() {
        return "text/x-java-source";
    }

    @Override
    public @NotNull String export(@NotNull GUI gui) {
        StringWriter writer = new StringWriter();
        try {
            export(gui, writer);
        } catch (IOException e) {
            // StringWriter 不会抛出 IOException
        }
        return writer.toString();
    }

    @Override
    public void export(@NotNull GUI gui, @NotNull Writer writer) throws IOException {
        String className = toClassName(gui.getId());

        writer.write("import com.thenextlvl.foliagui.builder.GUIBuilder;\n");
        writer.write("import com.thenextlvl.foliagui.builder.ItemBuilder;\n");
        writer.write("import org.bukkit.Material;\n");
        writer.write("import com.thenextlvl.foliagui.manager.GUIManager;\n\n");

        writer.write("/**\n");
        writer.write(" * GUI: " + gui.getId() + "\n");
        writer.write(" * Auto-generated by FoliaGUI Exporter\n");
        writer.write(" */\n");
        writer.write("public class " + className + "GUI {\n\n");

        writer.write("    public static void register(GUIManager manager) {\n");
        writer.write("        manager.register(create());\n");
        writer.write("    }\n\n");

        writer.write("    public static GUI create() {\n");
        writer.write("        return GUIBuilder.create(\"" + gui.getId() + "\")\n");

        if (gui.getInventory() != null) {
            int size = gui.getInventory().getSize();

            writer.write("            .rows(" + (size / 9) + ")\n");
        }

        writer.write("            // TODO: Add components here\n");
        writer.write("            // .button(slot, item, handler)\n");
        writer.write("            // .decoration(slot, item)\n");

        writer.write("            .build();\n");
        writer.write("    }\n");
        writer.write("}\n");
    }

    /**
     * 生成 ItemStack 创建代码
     */
    public static String generateItemStackCode(ItemStack item) {
        if (item == null || item.getType() == Material.AIR) {
            return "new ItemStack(Material.AIR)";
        }

        StringBuilder sb = new StringBuilder();
        sb.append("ItemBuilder.of(Material.").append(item.getType().name()).append(")");

        ItemMeta meta = item.getItemMeta();
        if (meta != null) {
            if (meta.hasDisplayName()) {
                sb.append("\n                .name(\"").append(escapeString(meta.getDisplayName())).append("\")");
            }
            if (meta.hasLore()) {
                for (String line : meta.getLore()) {
                    sb.append("\n                .lore(\"").append(escapeString(line)).append("\")");
                }
            }
        }

        sb.append("\n                .build()");
        return sb.toString();
    }

    private String toClassName(String id) {
        StringBuilder sb = new StringBuilder();
        boolean capitalizeNext = true;
        for (char c : id.toCharArray()) {
            if (Character.isLetterOrDigit(c)) {
                sb.append(capitalizeNext ? Character.toUpperCase(c) : c);
                capitalizeNext = false;
            } else {
                capitalizeNext = true;
            }
        }
        return sb.toString();
    }

    private static String escapeString(String str) {
        if (str == null) return "";
        return str
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t");
    }
}