package com.thenextlvl.foliagui.internal.export;

import com.thenextlvl.foliagui.api.GUI;
import com.thenextlvl.foliagui.api.export.GUIExporter;
import org.bukkit.inventory.ItemStack;
import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.io.StringWriter;
import java.io.Writer;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * YAML 格式导出器
 *
 * @author TheNextLvl
 */
public class YamlExporter implements GUIExporter {

    @Override
    public @NotNull String getFormat() {
        return "YAML";
    }

    @Override
    public @NotNull String getFileExtension() {
        return "yml";
    }

    @Override
    public @NotNull String getContentType() {
        return "application/x-yaml";
    }

    @Override
    public @NotNull String export(@NotNull GUI gui) {
        StringWriter writer = new StringWriter();
        try {
            export(gui, writer);
        } catch (IOException e) {
            // StringWriter 不会抛出 IOException
        }
        return writer.toString();
    }

    @Override
    public void export(@NotNull GUI gui, @NotNull Writer writer) throws IOException {
        Map<String, Object> config = buildConfigMap(gui);
        writeYaml(config, writer);
    }

    /**
     * 构建 GUI 配置 Map
     */
    private Map<String, Object> buildConfigMap(@NotNull GUI gui) {
        Map<String, Object> config = new LinkedHashMap<>();
        config.put("id", gui.getId());

        // 基础信息
        Map<String, Object> settings = new LinkedHashMap<>();
        if (gui.getInventory() != null) {
            settings.put("size", gui.getInventory().getSize());
        }
        config.put("settings", settings);

        // 组件信息需要从 GUI 实现 中获取
        // 这里提供基础框架，具体实现需要 AbstractGUI 支持

        return config;
    }

    /**
     * 简单的 YAML 写入器
     */
    private void writeYaml(Map<String, Object> config, Writer writer) throws IOException {
        writeHeader(writer);
        writeMap(config, writer, 0);
    }

    private void writeHeader(Writer writer) throws IOException {
        writer.write("# FoliaGUI Configuration\n");
        writer.write("# Generated by FoliaGUI Exporter\n\n");
    }

    private void writeMap(Map<String, Object> map, Writer writer, int indent) throws IOException {
        for (Map.Entry<String, Object> entry : map.entrySet()) {
            writeIndent(writer, indent);
            writer.write(entry.getKey());
            writer.write(": ");

            Object value = entry.getValue();
            if (value instanceof Map) {
                writer.write("\n");
                writeMap((Map<String, Object>) value, writer, indent + 2);
            } else if (value instanceof Iterable) {
                writer.write("\n");
                for (Object item : (Iterable<?>) value) {
                    writeIndent(writer, indent + 2);
                    writer.write("- ");
                    if (item instanceof Map) {
                        writer.write("\n");
                        writeMap((Map<String, Object>) item, writer, indent + 4);
                    } else {
                        writer.write(escapeValue(item));
                    }
                    writer.write("\n");
                }
            } else {
                writer.write(escapeValue(value));
                writer.write("\n");
            }
        }
    }

    private void writeIndent(Writer writer, int indent) throws IOException {
        for (int i = 0; i < indent; i++) {
            writer.write(' ');
        }
    }

    private String escapeValue(Object value) {
        if (value == null) {
            return "null";
        }
        String str = value.toString();
        // 简单的字符串转义
        if (str.contains(":") || str.contains("#") || str.contains("'") || str.contains("\"") || str.isEmpty()) {
            return "\"" + str.replace("\"", "\\\"") + "\"";
        }
        return str;
    }
}